#!/bin/bash 
# Add new vhost and ftp user to the system, optionally also
# new mysql database

VHOST=$1
USER=$VHOST
DB_NAME=$2
HERE=$(dirname $(readlink -f $0))

if [ "$(id -u)" != "0" ]; then
    echo 'Please run this script as root - HINT: use sudo'
    exit
fi

if [ -z "$VHOST" ]; then
    echo "Usage: $0 VHOST [DB]"
    echo 
    echo 'Create new vhost, ftp user and optionally new db.'
    echo 'The ftp username is the vhost, password is randomly'
    echo 'generated'
    exit
fi

if [ -f /etc/apache2/sites-available/${VHOST}.conf ]; then
    echo "The site ${VHOST} already exists!"
    exit
fi

success(){
    local ip=$(wget -q -O- http://checkip.dyndns.org | egrep -o '[0-9\.]+')
    local domainname=$(host $ip | cut -d' ' -f5)
    # chop away the trailing .
    domainname=${domainname::-1}

    cat << EOF

----------- Send this as email to customer ------

Information about access to you new site: ${VHOST}

Server:                 ${domainname}
Ip:                     ${ip}

FTP Server:		${domainname}
FTP Brugernavn:		${VHOST}
FTP Adgangskode:	${PASS}

EOF

    if [ ! -z "$DB_NAME" ]; then
	cat <<EOF
MySQL Server:		localhost
MySQL Brugernavn:	${DB_NAME}
MySQL Adgangskode:	${PASS}
MySQL Database:		${DB_NAME}

PHPMyAdmin:             ${domainname}/phpmyadmin

EOF
    fi
    
    cat <<EOF

You should add a DNS CNAME record to ${domainname}
----------------------------------------------------
EOF
}

PASS=$(pwgen -1)

./add_user "${USER}" "${PASS}"
./add_vhost "${VHOST}"
./add_ftp "${USER}" "${PASS}"

if [ ! -z "$DB_NAME" ]; then
    ./add_db "${USER}" "${PASS}" "${DB_NAME}"
fi

success
