#!/usr/bin/env bash
USER=$1
PASS=$2

if [ -z "$PASS" ]; then
    echo "Usage: $0 USER PASS"
    exit
fi

PASS=$(pwgen -1)
HASH=$(mkpasswd -m sha-512 ${PASS})

echo "${USER}:${HASH}" >> /etc/vsftpd/passwd
